/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg_vista;

import javax.swing.JButton;

/**
 *
 * @author uli08
 */
public class vistaTablaPacientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vistaTablaPacientes.class.getName());

    /**
     * Creates new form vistaTablaPacientes
     */
    public vistaTablaPacientes() {
        initComponents();
    }
    public javax.swing.JTable getTblPacientes() { return tblPacientes; }
    public javax.swing.JButton getBtnVolver() { return btnEliminarPa; }
    public javax.swing.JButton getBtnActualizarPa() { return btnActualizarPa; }
    public javax.swing.JButton getBtnEliminarPa() {return btnEliminarPa;}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaPacientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btnEliminarPa = new javax.swing.JButton();
        btnVolver1 = new javax.swing.JButton();
        btnActualizarPa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblListaPacientes.setFont(new java.awt.Font("DynaPuff SemiCondensed SemiBold", 0, 24)); // NOI18N
        lblListaPacientes.setForeground(new java.awt.Color(0, 0, 102));
        lblListaPacientes.setText("Lista de Pacientes");

        jScrollPane1.setBackground(new java.awt.Color(226, 233, 249));
        jScrollPane1.setForeground(new java.awt.Color(0, 51, 102));

        tblPacientes.setFont(new java.awt.Font("DynaPuff", 0, 12)); // NOI18N
        tblPacientes.setForeground(new java.awt.Color(0, 51, 102));
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Edad", "Telefono", "Alergias", "TipoDeSangre"
            }
        ));
        jScrollPane1.setViewportView(tblPacientes);

        btnEliminarPa.setFont(new java.awt.Font("DynaPuff", 0, 12)); // NOI18N
        btnEliminarPa.setForeground(new java.awt.Color(0, 0, 102));
        btnEliminarPa.setText("Eliminar");

        btnVolver1.setFont(new java.awt.Font("DynaPuff", 0, 12)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(0, 0, 102));
        btnVolver1.setText("Volver al Menú");

        btnActualizarPa.setFont(new java.awt.Font("DynaPuff", 0, 12)); // NOI18N
        btnActualizarPa.setForeground(new java.awt.Color(0, 0, 102));
        btnActualizarPa.setText("Actualizar");
        btnActualizarPa.addActionListener(this::btnActualizarPaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lblListaPacientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnVolver1)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarPa)
                .addGap(30, 30, 30)
                .addComponent(btnActualizarPa)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblListaPacientes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPa)
                    .addComponent(btnActualizarPa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnVolver1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarPaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vistaTablaPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarPa;
    public javax.swing.JButton btnEliminarPa;
    public javax.swing.JButton btnVolver1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblListaPacientes;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables
}
